version: '2'
services:
  cassandra:
    image: graanjonlo/cassandra:3.9
    ports:
     - "7000-7001:7000-7001"
     - "9042:9042"
     - "9160:9160"
    expose:
     - "7000-7001"
     - "9042"
     - "9160"
    volumes:
     - "/home/andy/docker/data/cassandra:/data"
     - "/home/andy/docker/logs/cassandra:/cassandra/logs"
    environment:
     - CLUSTER_NAME=mycluster